version '3'

networks:
  echonet:

services:
  mongo:
    image: mongo
    container_name: echo-mongo
    ports:
      -"27017"
  hub:
    image: birm/deployment_hub
    container_name: echo-hub
    ports:
      -"8080"
  api_node:
    image: birm/dh_api_node:latest
    container_name: echo-api
    depends_on:
      - "mongo"
    ports:
      -"8081:8081"
    environment:
      "mongo_host": "echo-mongo"
      "hub_url": "echo-hub:8080"
  echo_srv:
    image: birm/dh_echo_app
    container_name: echo-srv
    ports:
      -"8082"
    environment:
      "hub_url": "echo-hub:8080"
  echo_frontend:
    image: birm/dh_echo_frontend
    container_name: echo-web
    ports:
      -"8083:80"
    environment:
      "api_url": "echo-api:8081"
