version: '3'

services:
  mongo:
    image: mongo
    container_name: echo-mongo
    ports:
      ["27017"]
  hub:
    build: "./deployment_hub"
    container_name: echo-hub
    expose:
      ["8080"]
    environment:
      "hub_pw": ${HUB_PW}
  api_node:
    build: "./dh_api_node"
    container_name: echo-api
    depends_on:
      - "mongo"
      - "hub"
    ports:
      ["8081:8081"]
    environment:
      "mongo_host": "echo-mongo:27017"
      "hub_url": "echo-hub:8080"
      "hub_pw": ${HUB_PW}
  echo_srv:
    build: "./dh_echo_app"
    container_name: echo-srv
    depends_on:
      - "hub"
    expose:
      ["8082"]
    environment:
      "hub_url": "echo-hub:8080"
      "hub_pw": ${HUB_PW}
      "hostname": "echo-srv:8082"
  echo_frontend:
    build: "./dh_echo_frontend"
    container_name: echo-web
    ports:
      ["80:8083"]
    environment:
      "api_url": "echo-api:8081"
